# Local development secrets file
# This file stops the "No secrets files found" messages when running locally

[ACCESS_CODES]
admin_code = "admin2024"
user_code = "user2024"

[PERSISTENT_DATA]
backup_timestamp = "2025-01-06T00:00:00"
items_count = 0
requests_count = 0

[PERSISTENT_DATA.access_codes]
admin_code = "admin2024"
user_code = "user2024"

# Note: This is just a placeholder file to stop the messages
# Your app will work normally with or without this file
